Homework1
made-ml-in-prod-2021/kbrodt pull request #2
Opened 2021-05-04 01:31 UTC by kbrodt

Сделаны все пункты из дз.

Модульная архитектура. Тесты на основные функции. В качестве трансформера используется простой сдвиг логнормальных численных данных к нормальному распределению. Было сделано решение отказаться от хардкода пайпланов в коде и переноса их полностью в конфиг. Теперь в конфиге можно указать сколь угодно сложную предобработку данных и код сам создаст нужный пайплайн с указаннаыми параметрами.

Например

```
feature_pipelines:
  - name: "numeric"
    pipelines:
      - name: "SimpleImputer"
        params: 
          strategy: "mean"
      - name: "StandardScaler"
    columns:
      - "age"

  - name: "log1p"
    pipelines:
      - name: "Log1p"
      - name: "StandardScaler"
    columns:
      - "oldpeak"

  - name: "categorical"
    pipelines:
      - name: "OneHotEncoder"
    columns:
      - "cp"
    
  - name: "binary"
    pipelines: "passthrough"
    columns:
      - "sex"
```

создаст пайплан
```
ColumnTransformer([
  (numeric", 
])
```

Работать с гидрой неудобно, я люблю писать на питоновском аргпарсере и самому контролировать что сохранять. Но в качестве примера (и доп. баллов :) используется гидра.

Все задания были выполнены, значит максимальный балл. Можно накинуть 3 балла за пре-коммит хуки.
38 + 3 = 41 балл

2021-05-04 11:30 UTC, Mikhail-M requested changes
Ну видно, что норм сделано, не для галочки=)
Накидывать сверх максимума, я увы не буду, но респект. 38, думаю -- да. 
Для начала прошу переместить все артефакты деятельности по этой дз(кроме .github) в еще одну папку папку ml_project, наверно мне стоило попонятнее выразиться -- идея в том, что для каждого дз будет своя папка(и поправить скрипты в actions).

2021-05-04 18:15 UTC, StepDan23 approved these changes
в целом все О'кейси, кажется только пару лишних скрытых файлов, типо .gitignore .flake8 и тд.

перед тем как назначить ревью неплохо было бы обьединить кометы в один, гуглится [git sqиush commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

2021-05-04 18:15 UTC, StepDan23 commented on ml_project/models/__init__.py
> +    return model
ого, очень прикольная конструкция, впервые такое вижу)

2021-05-04 20:06 UTC, kbrodt commented on ml_project/features/transformers.py
> +        # Xo = Xo.values
не заметил, спасибо!

2021-05-04 20:11 UTC, kbrodt commented
Перенес проект в отдельный каталог, чтобы не конфликтовать со следующими дз. Узнал про `working-directory` для гитхаб событий. `git sqиush commits` боюсь тестировать на текущем пр, учту в будущем, спасибо! Все файлы типа .flake8 нужны для процесса разработки и фиксации гитхаб событий для линтера и тестера.

2021-05-04 20:54 UTC, kbrodt commented
Перенес `train.py/predict.py` в `tools`, так как это пользовательский код, который использует нашу "библиотеку".

2021-05-05 07:51 UTC, Mikhail-M commented on ml_project/features/transformers.py
> +        # Xo = Xo.values
> в целом все О'кейси, кажется только пару лишних скрытых файлов, типо .gitignore .flake8 и тд.
> 
> перед тем как назначить ревью неплохо было бы обьединить коммиты в один, гуглится [git sqиush commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

Насчет объединять коммиты в один -- не согласен. Наоборот, считается хорошей практикой делать небольшие атомарные коммиты. Конечно в некоторых местах(например, при реквестах в open source проекты) принято приводить историю коммитов в порядок, но это не в один коммит, а как раз в 5-к цельных через которые видна эволюция PR так сказать. Делается через git rebase и git push --force.  Но да, порой стремновато использовать. 

PS: 
В гитхабе будет возможность при мердже выбрать squash и тогда в main все изменению из этого PR будут в одном коммите.

2021-05-05 08:00 UTC, Mikhail-M requested changes
В общем вот это бы поправить ещё

2021-05-05 08:00 UTC, Mikhail-M commented on ml_project/clfit/apis/serialize.py
> +) -> None:
В typing есть NoReturn для такого, кстати
https://stackoverflow.com/questions/48038149/noreturn-vs-none-in-void-functions-type-annotations-in-python-3-6

2021-05-05 14:06 UTC, kbrodt commented on ml_project/clfit/features/transformers.py
> +SimpleImputer = SimpleImputer
Я хочу использовать мощь питона `getattr` и не писать кучу ифоф для выбора трансформера. Поэтому все трансформеры из разных сабмодулей склёрна импортируются в один. А чтобы майпай не ругался, что имеются не используемые переменные, то я насильно завожу алиасы. Можно даже коротие имена дать, чтобы в конфиге не писать длиные названия

2021-05-05 14:06 UTC, kbrodt commented on ml_project/clfit/apis/serialize.py
> +) -> None:
Не согласен. NoReturn означает, что функция никогда не возвратит значение, у меня она возвращает None.

2021-05-05 14:11 UTC, kbrodt commented on ml_project/tests/train_test.py
> +    faker.set_arguments("num", {"min_value": 1, "max_value": 100})
Думал об этом. Попробую.

У нас нет контретного гайдлайна, поэтому я испрользую тот, который мне удобен. `pytest` не запрещает использовать оба. Я использую для файлов порядок `*_test` чтобы: 1) сразу по первым буквам понимать о чём тест, 2) при работе в терминале не писать неинформативное слово `test_` 3) при грепе можно быстро визуально отличить файл от функции

2021-05-05 16:27 UTC, kbrodt commented
Вынес копипасту из тестов в `conftest.py`. Теперь тесты для `{train,predict}_test.py` выглядят лаконично

2021-05-05 16:48 UTC, Mikhail-M commented
Нажимайте на re-request review когда смотреть смотреть снова надо -- удобный ui
допроверю завтра

2021-05-06 11:54 UTC, Mikhail-M approved these changes
Баллы: 38

2021-05-06 13:10 UTC, merged

2021-05-09 21:27 UTC, cherninkiy commented
А с меня звездочка. Крутая работа!

2021-05-10 00:07 UTC, kbrodt commented
Спасибо!